### ISSUE TITLE
Limit storage indicator endpoint to current user

### ISSUE THREAD

**Issue by ajaniramon** [internxt/X-Cloud-Server#10]
Currently storage and limit endpoints show the disk usage by reading a parameter on request body. This is insecure because  a regular user can see the storage and the subscription plan of other uses. 

Also this is non REST compliant because a parameter must be send on request uri via query string or in the uri itself (and has to use GET http verb, instead of POST). 

I suggest to have an endpoint where the caller JWT is read and caller ID is retrieved, so system queries only the caller disk usage.

**Comment by JAlbertoGonzalez** [comment]
Fixed 😊
